spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: Welcome1
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/main.xml